<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fal_profile"
 *
 * Auto generated by Extension Builder 2013-03-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Profile processing for File Abstraction Layer',
	'description' => 'Profile processing for File Abstraction Layer',
	'category' => 'plugin',
	'author' => 'Oliver Hader',
	'author_email' => 'oliver.hader@typo3.org',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '',
	'createDirs' => 'uploads/fal_profile',
	'modify_tables' => 'sys_file_storage',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>